#!/bin/bash

# Variables
BASE=/home/hritik/scripts
DAYS=10
DEPTH=1
RUN=0

# Check if the directory is present or not

if [ ! -d "$BASE" ]
then
    echo "Directory does not exist: $BASE"
    exit 1
fi

# Create 'archive' folder if not present

if [ ! -d "$BASE/archive" ]
then
    mkdir -p "$BASE/archive"
fi

# Find files older than 10 days and larger than 20 MB

for i in $(find "$BASE" -maxdepth "$DEPTH" -type f -mtime +"$DAYS" -size +20M)
do
    if [ "$RUN" -eq 0 ]
    then
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Archiving $i ==> $BASE/archive"
        gzip "$i" || exit 1
        mv "$i.gz" "$BASE/archive" || exit 1
    fi
done
