#!/bin/bash

# Monitoring the free disk space

FU=$(df -h | egrep -v "Filesystem|tmpfs" | grep "sda2" | awk '{print $5}' | tr -d '%')

TO="hritik7024@gmail.com"

if [[ $FU -ge 20 ]]
then
    echo "Warning, disk space is low - ${FU}%" | mail -s "DISK SPACE ALERT!" "$TO"
else
    echo "ALL GOOD"
fi
