#!/bin/bash

# Script should be executed with sudo/root access

if [[ "${UID}" -ne 0 ]]
then
    echo "Please run with sudo or root user"
    exit 1
fi

# User should provide at least one argument as username

if [[ "${#}" -lt 1 ]]
then
    echo "Usage: ${0} USER_NAME [COMMENT]..."
    echo "Create a user with USER_NAME and comments field."
    exit 1
fi

# Store first argument as username
USER_NAME="${1}"
echo "$USER_NAME"

# Store remaining arguments as account comments
shift
COMMENT="${@}"
echo "$COMMENT"

# Create a password
PASSWORD=$(date +%S%N)
echo "$PASSWORD"

# Create the user
useradd -c "${COMMENT}" -m "$USER_NAME"

# Check if user is successfully created or not

if [[ $? -ne 0 ]]
then
    echo "The account could not be created."
    exit 1
fi

# Set the password for the user
echo "$PASSWORD" | passwd --stdin "$USER_NAME"

# Check if the password is successfully created or not

if [[ $? -ne 0 ]]
then
    echo "Password could not be set."
    exit 1
fi

# Force password change on first login
passwd -e "$USER_NAME"

# Display the username, password and host

echo
echo "Username : $USER_NAME"
echo "Password : $PASSWORD"
echo "Hostname : $(hostname)"
